using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(MeshFilter))]
[RequireComponent(typeof(MeshRenderer))]

public class TriangleGenerator : MonoBehaviour
{

    [SerializeField]
    private Vector3 size = Vector3.one;

    private List<Material> materialList;


    void Start()
    {
        //initialise mesh filter
        MeshFilter meshFilter = this.GetComponent<MeshFilter>();

        //initialise mesh generator
        MeshGenerator mg = new MeshGenerator(1);

        //building triangle
        Vector3 p0 = new Vector3(size.x,  size.y, -size.z);
        Vector3 p1 = new Vector3(-size.x, size.y, -size.z);
        Vector3 p2 = new Vector3(-size.x, size.y,  size.z);

        mg.BuildTriangle(p0, p1, p2, 0);


        //mesh filter's mesh to the one generated by the mesh generator
        meshFilter.mesh = mg.CreateMesh();

        //5. initialise mesh renderer and assign material list to the mesh renderer's materials list
        MeshRenderer meshRenderer = this.GetComponent<MeshRenderer>();
        AddMaterials();
        meshRenderer.materials = materialList.ToArray();
    }

    private void AddMaterials()
    {
        Material greenMat = new Material(Shader.Find("Specular"));
        greenMat.color = Color.green;

        materialList = new List<Material>();
        materialList.Add(greenMat);
    }
}
